[package]
name = "parse-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["bytes"]
bytes = ["dep:bytes"]

[dependencies]
bytes = { version = "1", optional = true }
thiserror = "1"
